FROM python:3.12-slim

WORKDIR /app

# Instala ferramentas necessárias para compilar dependências se precisar
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo o código fonte
COPY . .

# Comando padrão, será sobreescrito pelo docker-compose
CMD ["python", "gateway/main.py"]
