# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\tsmartcity\"Z\n\x10\x44iscoveryRequest\x12\x12\n\ngateway_ip\x18\x01 \x01(\t\x12\x18\n\x10gateway_udp_port\x18\x02 \x01(\x05\x12\x18\n\x10gateway_tcp_port\x18\x03 \x01(\x05\"i\n\x11\x44iscoveryResponse\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x10\n\x08tcp_port\x18\x04 \x01(\x05\x12\x15\n\rinitial_state\x18\x05 \x01(\t\"^\n\x0b\x44\x61taReading\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x0c\n\x04unit\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"G\n\x0e\x43ontrolCommand\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x11\n\tparameter\x18\x03 \x01(\t\"F\n\x0f\x43ontrolResponse\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"\xe8\x01\n\rClientRequest\x12\x32\n\x04type\x18\x01 \x01(\x0e\x32$.smartcity.ClientRequest.RequestType\x12\x32\n\x0f\x63ontrol_command\x18\x02 \x01(\x0b\x32\x19.smartcity.ControlCommand\x12\x13\n\x0b\x66ilter_type\x18\x03 \x01(\t\"Z\n\x0bRequestType\x12\x10\n\x0cLIST_SOURCES\x10\x00\x12\x13\n\x0f\x43ONTROL_COMMAND\x10\x01\x12\x0f\n\x0bGET_HISTORY\x10\x02\x12\x13\n\x0fGET_AGGREGATION\x10\x03\"<\n\nSourceInfo\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\"\x9f\x01\n\x0e\x43lientResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12&\n\x07sources\x18\x03 \x03(\x0b\x32\x15.smartcity.SourceInfo\x12\'\n\x07history\x18\x04 \x03(\x0b\x32\x16.smartcity.DataReading\x12\x1a\n\x12\x61ggregation_result\x18\x05 \x01(\x01\x42\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_DISCOVERYREQUEST']._serialized_start=29
  _globals['_DISCOVERYREQUEST']._serialized_end=119
  _globals['_DISCOVERYRESPONSE']._serialized_start=121
  _globals['_DISCOVERYRESPONSE']._serialized_end=226
  _globals['_DATAREADING']._serialized_start=228
  _globals['_DATAREADING']._serialized_end=322
  _globals['_CONTROLCOMMAND']._serialized_start=324
  _globals['_CONTROLCOMMAND']._serialized_end=395
  _globals['_CONTROLRESPONSE']._serialized_start=397
  _globals['_CONTROLRESPONSE']._serialized_end=467
  _globals['_CLIENTREQUEST']._serialized_start=470
  _globals['_CLIENTREQUEST']._serialized_end=702
  _globals['_CLIENTREQUEST_REQUESTTYPE']._serialized_start=612
  _globals['_CLIENTREQUEST_REQUESTTYPE']._serialized_end=702
  _globals['_SOURCEINFO']._serialized_start=704
  _globals['_SOURCEINFO']._serialized_end=764
  _globals['_CLIENTRESPONSE']._serialized_start=767
  _globals['_CLIENTRESPONSE']._serialized_end=926
# @@protoc_insertion_point(module_scope)
